name: 'springboot-microservices-bookstore'
services:
  catalog-service:
    image: manoadhi/bs-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:mysql://catalog-db:3306/bookstore
      - DB_USERNAME=appuser
      - DB_PASSWORD=apppass
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m