name: springboot-microservice-bookstore

services:
  catalog-db:
    image: mysql:8.4
    container_name: catalog-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      DB_URL: jdbc:mysql://localhost:3306/bookstore
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

